# fields and their validators
# a validator can be a type, a requred value, a list of forbidden values, or any other custom function
# every field can have a type, functions
# every function can have an args list, kwargs list
# the args and kwargs list must be numbered: one, two, three ...
# every kwargs item must have a name and val
# coerce
# forbidden_values
order_fields_validators:
    required_fields:
        id:
            functions:
                CoerceTo:
                    kwargs:
                        typ: int
                        column_name: order_id

        name:
            type: str
            functions:
                LengthCustom:
                    kwargs:
                        min: 1
                        max: 120

    optional_fields:
        email:
            type: str
            functions:
                MatchesEmailRegEx:
                    kwargs:
                        msg: $INVALID_EMAIL_ERROR
                LengthCustom:
                    kwargs:
                        max: 120
        birthday:
            functions:            
                CoerceTo:
                    kwargs:
                        typ: date
                        converter_function: convert_to_date
                        column_name: birthday
                        msg: $COERCE_DATE_ERROR
                DateRange:
                    kwargs:
                        max: $TODAY_LESS_21_YEARS
            functions_order: [CoerceTo, DateRange]
        zipcode:
            functions:
                CoerceTo:
                    kwargs:
                        typ: int
                        column_name: zipcode
                        msg: $COERCE_INT_ERROR
                LengthIn:
                    kwargs:
                        container: $ZIPCODE_LENGTHS
                        msg: $LENGTH_CHOICE_ERROR_ZIPCODE
                SumMax:
                    kwargs:
                        max_sum: $MAX_ZIPCODE_SUM
            functions_order: [CoerceTo, LengthIn, SumMax]
        state:
            type: str
            functions:
                ValueNotIn:
                    kwargs:
                        container: $FORBIDDEN_STATES
                        column_name: state
    dependent_fields:
        qualifier: Any
        msg: $NY_EMAIL_ERROR
        Or:
            And:
                state:
                    value: NY
                email:
                    functions:
                        EndsWith:
                            kwargs:
                                ending: .net
                                allowed: false
            state:
                functions:
                    In:
                        kwargs:
                            container: $STATES_LESS_NY




order_fields_defaults:
    birthday:
        coerce_failure_msg: $COERCE_DATE_ERROR
        failure_value: null
    zipcode:
        coerce_failure_msg: $COERCE_INT_ERROR
        failure_value: null


