# fields and their validators
# a validator can be a type, a requred value, a list of forbidden values, or any other custom function
# every field can have a type, functions
# every function can have an args list, kwargs list
# the args and kwargs list must be numbered: one, two, three ...
# every kwargs item must have a name and val
# coerce
# forbidden_values
order_fields_validators:
    required_fields:
        id:
            functions:
                CoerceTo:
                    kwargs:
                        typ: int
                        column_name: order_id

        name:
            type: str
            functions:
                Length:
                    kwargs:
                        min: 1
    optional_fields:
        email:
            type: str
        birthday:
            functions:                
                CoerceTo:
                    kwargs:
                        converter_function: convert_to_date
                        column_name: birthday
                        msg: $COERCE_DATE_ERROR
                DateRange:
                    kwargs:
                        max: $TODAY_LESS_21_YEARS                
        zipcode:
            functions:
                LengthIn:
                    kwargs:
                        container: $ZIPCODE_LENGTHS
                CoerceTo:
                    kwargs:
                        typ: int
                        column_name: zipcode
        state:
            type: str
            functions:
                # Upper:

                ValueNotIn:
                    kwargs:
                        container: $FORBIDDEN_STATES
                        column_name: state

order_fields_defaults:
    birthday:
        coerce_failure_msg: $COERCE_DATE_ERROR
        failure_value: null
    zipcode:
        failure_value: null


